package:
    type:           yii2-extension
    name:           yii2-asset-advancedhosters
    title:          'AdvancedHosters asset files: images, configs and more'
    headline:       AdvancedHosters assets
    keywords:       advancedhosters, asset, extension, yii2
    namespace:      advancedhosters\assets\advancedhosters
    description:    |
        [AdvancedHosters](https://advancedhosters.com) is a domain registrator.

        This package provides assets shareable between different AdvancedHosters projects:

        - logos and css bundled with yii2 asset bundle
        - config settings
        - translations

